name: Dispatcher Workflow

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Queue Build
        run: echo "Build job queued"
