on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build_LIVE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get Branch Name
        id: vars
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')"

      - name: Trigger Regression Tests for LIVE ENV
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: dubeywati
          workflow_file_name: main.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}", "ENV_NAME": "LIVE" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}

  build_Trail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get Branch Name
        id: vars
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')"

      - name: Trigger Regression Tests for Trail ENV
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: dubeywati
          workflow_file_name: trail.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}", "ENV_NAME": "Trail" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}
