on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build_LIVE:
    runs-on: ubuntu-latest
    steps:
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: vars
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
      - run: echo ${{ steps.vars.outputs.branch }}
      
      - name: Checkout  
        uses: actions/checkout@v1
        with:
          ref: ${{ steps.vars.outputs.branch }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      

      - name: Trigger Regression Tests for LIVE ENV
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: dubeywati
          workflow_file_name: main.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{  github.event.repository.name }}"}'
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}

  build_Trail:
    runs-on: ubuntu-latest
    steps:
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: vars
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
      - run: echo ${{ steps.vars.outputs.branch }}
      
      - name: Checkout  
        uses: actions/checkout@v1
        with:
          ref: ${{ steps.vars.outputs.branch }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Trigger Regression Tests for Trail ENV
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: dubeywati
          workflow_file_name: trail.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{  github.event.repository.name }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}



# name: Regression Tests

# on:
#   pull_request:
#     branches:
#       - 'main'
#       - 'master'

# jobs:
#   common_setup:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mdecoleman/pr-branch-name@1.2.0
#         id: vars
#         with:
#           repo-token: ${{ secrets.PAT_TOKEN }}
#       - run: echo ${{ steps.vars.outputs.branch }}
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ steps.vars.outputs.branch }}
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 6.0.x

#   build_LIVE:
#     runs-on: ubuntu-latest
#     needs: common_setup
#     steps:
#       - name: Trigger Regression Tests for LIVE ENV
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: main.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ needs.common_setup.outputs.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'

#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

#   build_Trail:
#     runs-on: ubuntu-latest
#     needs: common_setup
#     steps:
#       - name: Trigger Regression Tests for Trail ENV
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: trail.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ needs.common_setup.outputs.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'
#           propagate_failure: true
#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

