# on:
#   pull_request:
#     branches:
#       - 'main'
#       - 'master'

# jobs:
#   build_LIVE:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mdecoleman/pr-branch-name@1.2.0
#         id: vars
#         with:
#           repo-token: ${{ secrets.PAT_TOKEN }}
#       - run: echo ${{ steps.vars.outputs.branch }}
      
#       - name: Checkout  
#         uses: actions/checkout@v1
#         with:
#           ref: ${{ steps.vars.outputs.branch }}

#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 6.0.x

#       - name: Trigger Regression Tests for LIVE ENV
#         id: live
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: main.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{  github.event.repository.name }}"}'
#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

#   build_Trail:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mdecoleman/pr-branch-name@1.2.0
#         id: vars
#         with:
#           repo-token: ${{ secrets.PAT_TOKEN }}
#       - run: echo ${{ steps.vars.outputs.branch }}
      
#       - name: Checkout  
#         uses: actions/checkout@v1
#         with:
#           ref: ${{ steps.vars.outputs.branch }}

#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 6.0.x

#       - name: Trigger Regression Tests for Trail ENV
#         id: trail
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: trail.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ steps.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{  github.event.repository.name }}"}'
#           propagate_failure: true
#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

# # Add the following step at the end of your workflow
#   comment_on_failure:
#     needs: [build_LIVE, build_Trail]  # Wait for the other jobs to complete
#     runs-on: ubuntu-latest
#     if: failure()  # Only execute this step if any of the previous jobs fail
#     env:
#       GH_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
#     steps:
#       - name: Combine Error Messages
#         run: |
#           LIVE_ERROR=$(echo "${{ steps.live.outputs.client_payload }}" | jq -r '.error_message')
#           TRAIL_ERROR=$(echo "${{ steps.trail.outputs.client_payload }}" | jq -r '.error_message')
#           COMMENT="Your workflow failed.\n\nLIVE ENV Error:\n$LIVE_ERROR\n\nTRAIL ENV Error:\n$TRAIL_ERROR"
#           echo "$COMMENT" > comment.txt
#       - name: Comment on PR on failure
#         run: |
#           PR_NUMBER="${{ github.event.pull_request.number }}"
#           COMMENT=$(cat comment.txt)
#           curl -s -X POST -H "Authorization: token $GH_PAT_TOKEN" -d "{\"body\":\"$COMMENT\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"




on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build_LIVE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Rest of your steps for build_LIVE job...

      - name: Trigger Regression Tests for LIVE ENV
        id: live
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKENS }}
          github_user: dubeywati
          workflow_file_name: main.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ github.event.pull_request.head.ref }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'
          trigger_workflow: true
          wait_workflow: true

  build_Trail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Rest of your steps for build_Trail job...

      - name: Trigger Regression Tests for Trail ENV
        id: trail
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKENS }}
          github_user: dubeywati
          workflow_file_name: trail.yml
          ref: feature
          wait_interval: 10
          client_payload: '{"branch_name":"${{ github.event.pull_request.head.ref }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  comment_on_failure:
    needs: [build_LIVE, build_Trail]  # Wait for the other jobs to complete
    runs-on: ubuntu-latest
    if: failure()  # Only execute this step if any of the previous jobs fail
    env:
      GH_PAT_TOKEN: ${{ secrets.PAT_TOKENS }}
    steps:
     - name: Extract Error Message
       id: extract_error_message
       run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKENS }}" "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments")
          ERROR_MESSAGE=""
          for COMMENT in $(echo "$COMMENTS" | jq -r '.[] | @base64'); do
            COMMENT_BODY=$(echo "$COMMENT" | base64 --decode | jq -r '.body')
            # Check if the comment contains an error message
            if echo "$COMMENT_BODY" | grep -q '❌ Job Failures:'; then
              ERROR_MESSAGE=$(echo "$COMMENT_BODY" | grep -A1 '❌ Job Failures:' | tail -n 1)
              break
            fi
          done
          echo "ERROR_MESSAGE=$ERROR_MESSAGE" >> $GITHUB_ENV

     - name: Comment on PR on failure
       run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENT=$(cat comment.txt)
          curl -s -X POST -H "Authorization: token $GH_PAT_TOKEN" -d "{\"body\":\"$COMMENT\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
       env:
          GH_PAT_TOKEN: ${{ secrets.PAT_TOKENS }}








# name: Regression Tests

# on:
#   pull_request:
#     branches:
#       - 'main'
#       - 'master'

# jobs:
#   common_setup:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mdecoleman/pr-branch-name@1.2.0
#         id: vars
#         with:
#           repo-token: ${{ secrets.PAT_TOKEN }}
#       - run: echo ${{ steps.vars.outputs.branch }}
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ steps.vars.outputs.branch }}
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 6.0.x

#   build_LIVE:
#     runs-on: ubuntu-latest
#     needs: common_setup
#     steps:
#       - name: Trigger Regression Tests for LIVE ENV
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: main.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ needs.common_setup.outputs.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'

#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

#   build_Trail:
#     runs-on: ubuntu-latest
#     needs: common_setup
#     steps:
#       - name: Trigger Regression Tests for Trail ENV
#         uses: convictional/trigger-workflow-and-wait@v1.6.5
#         with:
#           owner: dubeywati
#           repo: test
#           github_token: ${{ secrets.PAT_TOKEN }}
#           github_user: dubeywati
#           workflow_file_name: trail.yml
#           ref: feature
#           wait_interval: 10
#           client_payload: '{"branch_name":"${{ needs.common_setup.outputs.vars.outputs.branch }}","PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}", "PR_REPO_OWNER": "${{ github.repository_owner }}", "PR_REPO_NAME": "${{ github.event.repository.name }}"}'
#           propagate_failure: true
#           trigger_workflow: true
#           wait_workflow: true
#           comment_downstream_url: ${{ github.event.pull_request.comments_url }}

