name: Push and Pull Request Workflow

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: vars
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}

      - name: Determine Event Type
        id: determine-event-type
        run: echo "EVENT_TYPE=$(if [[ -n '${{ github.event.pull_request.number }}' ]]; then echo 'pull_request'; else echo 'push'; fi)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Executing Regression Tests
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: dubeywati
          repo: test
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: dubeywati
          workflow_file_name: main.yml
          ref: ${{ github.ref }}
          wait_interval: 10
          client_payload: |
            {
              "branch_name": "${{ steps.vars.outputs.branch }}",
              "EVENT_TYPE": "${{ env.EVENT_TYPE }}",
              "PR_ISSUE_NUMBER": "${{ github.event.pull_request.number }}",
              "PR_REPO_OWNER": "${{ github.repository_owner }}",
              "PR_REPO_NAME": "${{ github.event.repository.name }}"
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.comment.url }}
